# Generated by Django 5.1.5 on 2025-02-04 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_transaction_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='issued_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='transaction',
        ),
        migrations.AddField(
            model_name='receipt',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_receipts', to='website.company'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='website.order'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued_receipts', to=settings.AUTH_USER_MODEL),
        ),
    ]
