# Generated by Django 5.1.5 on 2025-02-04 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_transaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.transaction'),
        ),
    ]
