# Generated by Django 5.1.5 on 2025-02-04 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_receipt_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='created_at',
            new_name='issued_at',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='company',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='order',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='seller',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='website.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='website.order'),
        ),
    ]
