# Generated by Django 5.1.5 on 2025-02-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_created_at_receipt_issued_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
