# Generated by Django 5.1.5 on 2025-02-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_issued_at_receipt_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='buyer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='total_price',
        ),
    ]
