# Generated by Django 5.1.5 on 2025-02-10 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_order_status_trackinglog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackinglog',
            old_name='update_timestamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='trackinglog',
            name='location',
        ),
        migrations.RemoveField(
            model_name='trackinglog',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='logistics_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='status_update',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], max_length=50),
        ),
    ]
