# Generated by Django 5.1.5 on 2025-02-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_trackinglog_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_name',
        ),
    ]
