# Generated by Django 5.1.5 on 2025-02-18 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_municipality_region_alter_profile_user_barangay_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinglog',
            name='transferred_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='status_update',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('handover', 'Handed Over')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
