# Generated by Django 5.1.5 on 2025-02-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_remove_trackinglog_transferred_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_been_transferred',
            field=models.BooleanField(default=False),
        ),
    ]
