# Generated by Django 5.1.5 on 2025-02-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_order_has_been_transferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
