# Generated by Django 5.1.5 on 2025-03-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_alter_trackinglog_status_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinglog',
            name='status_update',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
    ]
