# Generated by Django 5.1.5 on 2025-03-14 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_remove_municipality_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.province'),
        ),
    ]
