# Generated by Django 5.1.5 on 2025-03-14 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_company_last_assigned_logistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='last_assigned_logistics',
        ),
    ]
