# Generated by Django 5.1.5 on 2025-03-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_picked_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Picked Up', 'Picked Up'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Arrived', 'Arrived'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='status_update',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Picked Up', 'Picked Up'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Arrived', 'Arrived'), ('Delivered', 'Delivered')], max_length=50),
        ),
    ]
