# Generated by Django 5.1.5 on 2025-03-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_remove_orderitem_is_picked_up_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
