# Generated by Django 5.1.5 on 2025-03-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0046_orderitem_is_picked_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Picked Up', 'Picked Up'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Arrived', 'Arrived'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='trackinglog',
            name='status_update',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Picked Up', 'Picked Up'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Arrived', 'Arrived'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
    ]
